# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0010_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_student', related_query_name='introduction_to_models_student', to='introduction_to_models.Car'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cars',
            field=models.ManyToManyField(related_name='introduction_to_models_teacher', related_query_name='introduction_to_models_teacher', to='introduction_to_models.Car'),
        ),
    ]
